### ISSUE TITLE
3builddistro-Z is skipping over the jwm & gtk themes setup

### ISSUE THREAD

**Issue by mrfricks** [puppylinux-woof-CE/woof-CE#649]
3builddistro-Z is skipping the point where you usually select which gtk/jwm theme, background picture and icon set . i'm getting no selection window and the script goes straight to set desktop text defaults colour
```
Finding invalid symlinks...
Updating pkg data in rootfs-complete/root/.packages ...
Rationalizing categories in Packages-puppy-tahr64-official, please wait...
Fixing: rootfs-complete/usr/share/themes/Flat-grey-rounded/gtk-2.0/gtkrc
Fixing: rootfs-complete/usr/share/themes/FlatBlueContrast/gtk-2.0/gtkrc
Fixing: rootfs-complete/root/.jwm/themes/DeepBlueBold-jwmrc
Fixing: rootfs-complete/root/.jwm/themes/bluevariety-jwmrc

Constructing configuration files for JWM, Fvwm95, IceWM, openbox...
Generating /root/.jwmrc...
cat: rootfs-complete/etc/desktop_icon_theme: No such file or directory


The ROX-Filer desktop text defaults to white with black shadow, but this is
not best for some light backgound images. ENTER only to keep, but if you
want black text press any printable key then ENTER:
```

an older 3builddistro-Z works fine

**Comment by 01micko** [comment]
I just pushed a bugfix. See if it works now.

**Comment by mrfricks** [comment]
no it's still not working for me.... and terminal messages the same as above

**Comment by 01micko** [comment]
Are you choosing to include ptheme in the checkboxes?

**Comment by 01micko** [comment]
Ok, there's a bug where ptheme hasn't been removed from the main rootfs-skeleton.

If you have a wallpaper named 'default.jpg or default.png please rename it and try again.

**Comment by mrfricks** [comment]
no i'm not including ptheme, the only things i've selected are firewall_ng & change_kernels.

none of the wallpapers are called default

**Comment by 01micko** [comment]
I just pushed another fix but *before* you run `merge2out` delete from your working woof dir tree`rootfs-skeleton/usr/share/ptheme/`. That should have been removed ages ago when the whole rootfs-packages thing started.

**Comment by mrfricks** [comment]
thanks .... it seems to be working now!

one thing, although i'm not using ptheme.. the option to use it is greyed out.

**Comment by 01micko** [comment]
Yes that is because you don't have this in your specs:

`yes|switch2||exe`

If you wanted to use ptheme switch2 is available in the petbuilds, or you can try the slacko versions for 32 and 64 respectively.

**Comment by 01micko** [comment]
Closing for now but if there is still an issue just re-open.
